Storage class sample
laljikanjareeya/nodejs-storage pull request #9
Opened 2020-09-01 12:56 UTC by laljikanjareeya

2020-09-03 14:41 UTC, AVaksman requested changes

2020-09-03 14:41 UTC, AVaksman commented on samples/createBucketWithStorageClassAndLocation.js
> +  storageClass = 'COLDLINE',
I believe this value should be in lower case as it will be the property name and property names are case sensitive.

refer [here](https://github.com/googleapis/nodejs-storage/blob/master/src/storage.ts#L77)

2020-09-03 14:41 UTC, AVaksman commented on samples/createBucketWithStorageClassAndLocation.js
> +      storageClass,
Based on the comment above I believe this should be as follows
```suggestion
      [storageClass]: true,
```

2020-09-03 15:42 UTC, laljikanjareeya commented on samples/createBucketWithStorageClassAndLocation.js
> +  storageClass = 'COLDLINE',
I have taken reference from [create bucket](https://github.com/googleapis/nodejs-storage/blob/master/samples/createNewBucket.js) existing sample.

2020-09-10 08:01 UTC, AVaksman commented on samples/createBucketWithStorageClassAndLocation.js
> +  storageClass = 'COLDLINE',
The above example will only work for `js` and will complain in `ts`. I think we should provide an example that goes along with the API. Meaning `coldline: true`

2020-09-10 08:20 UTC, AVaksman requested changes

2020-09-10 08:20 UTC, AVaksman commented on samples/fileChangeStorageClass.js
> +    });
I get `Error: Invalid argument` Error with this set up. It seems that existing file's storageClass does not change.
I believe [`file#setStorageClass()`](https://github.com/googleapis/nodejs-storage/blob/master/src/file.ts#L3451) function should be used, which accomplishes setting a different `storageClass` via `file#copy`

2020-09-11 04:14 UTC, closed without merging

2020-09-11 14:16 UTC, AVaksman commented on samples/fileChangeStorageClass.js
> +  storageClass = 'STANDARD'
Can we do lower case? as per [docs](https://googleapis.dev/nodejs/storage/latest/Bucket.html#setStorageClass)

2020-09-11 14:16 UTC, AVaksman commented on samples/changeDefaultStorageClass.js
> +function main(bucketName = 'my-bucket', storageClass = 'STANDARD') {
lower case for `'STANDARD'` here as well please

2020-09-11 14:16 UTC, AVaksman commented on samples/changeDefaultStorageClass.js
> +  // const storageClass = 'Name of a storage class, e.g. STANDARD';
Lower case in documentation as well

2020-09-11 14:16 UTC, AVaksman commented on samples/fileChangeStorageClass.js
> +  // const storageClass = 'Name of a storage class, e.g. STANDARD';
Lower case in documentation as well

2020-09-11 14:16 UTC, AVaksman commented on samples/system-test/buckets.test.js
> +    `node changeDefaultStorageClass.js ${bucketName} COLDLINE`
Lower case please here and in other tests please